apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "allure-helmify.fullname" . }}-ingress-service-load-balancer
  labels:
  {{- include "allure-helmify.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localdomain.at
    http:
      paths:
      - backend:
          service:
            name: '{{ include "allure-helmify.fullname" . }}-service-load-balancer'
            port:
              number: 6060
        path: /allure-api/?(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "allure-helmify.fullname" . }}-service-load-balancer'
            port:
              number: 7070
        path: /allure-ui/?(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "allure-helmify.fullname" . }}-service-load-balancer'
            port:
              number: 7070
        path: /?(.*)
        pathType: Prefix
  tls:
  - hosts:
    - localdomain.at
    secretName: local-domain-at-tls