apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "allure-helmify.fullname" . }}-persistent-volume-claim
  labels:
  {{- include "allure-helmify.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.persistentVolumeClaim.storageRequest | quote }}
  volumeMode: Filesystem