apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "allure-helmify.fullname" . }}-persistent-volume
  labels:
  {{- include "allure-helmify.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /allure/projects
  volumeMode: Filesystem