apiVersion: v1
kind: Secret
metadata:
  name: {{ include "allure-helmify.fullname" . }}-secret
  labels:
  {{- include "allure-helmify.labels" . | nindent 4 }}
data:
  SECURITY_PASS: {{ required "secret.securityPass is required" .Values.secret.securityPass
    | b64enc | quote }}
  SECURITY_USER: {{ required "secret.securityUser is required" .Values.secret.securityUser
    | b64enc | quote }}
  SECURITY_VIEWER_PASS: {{ required "secret.securityViewerPass is required" .Values.secret.securityViewerPass
    | b64enc | quote }}
  SECURITY_VIEWER_USER: {{ required "secret.securityViewerUser is required" .Values.secret.securityViewerUser
    | b64enc | quote }}
type: Opaque