apiVersion: v1
kind: Service
metadata:
  name: {{ include "allure-helmify.fullname" . }}-service-load-balancer
  labels:
  {{- include "allure-helmify.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceLoadBalancer.type }}
  selector:
    type: app
  {{- include "allure-helmify.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.serviceLoadBalancer.ports | toYaml | nindent 2 -}}